name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # Tự động chạy mỗi ngày
  workflow_dispatch: # Cho phép bấm chạy thủ công

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update LeetCode Stats in README
        uses: joshcai/leetcode-sync@v1.0.5
        with:
          username: khiemvuong2310
          # Action này chỉ cần đọc public API nên không yêu cầu METRICS_TOKEN phức tạp
